Repository opensearch-project/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#164 Updated OpenSearch appVersion to 1.2.1
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: good first issue

#185 [Re-PR of #84] Fixing Service Name References When Using fullnameOverride For Masters
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/_helpers.tpl
  charts/opensearch/templates/ingress.yaml
  charts/opensearch/templates/service.yaml
  charts/opensearch/templates/statefulset.yaml
Labels: 1.5.6

#179 Upgrade default OpenSearch version to 1.2.3
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: 1.5.7
