Repository opensearch-project/helm-charts, pull requests merged in 2022-06, with the labels that each got.

#172 Add Readiness probe to OpenSearch Chart
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/README.md
  charts/opensearch/ci/ci-ingress-class-name-values.yaml
  charts/opensearch/ci/ci-rbac-enabled-values.yaml
  charts/opensearch/ci/ci-values.yaml
  charts/opensearch/templates/statefulset.yaml
  charts/opensearch/values.yaml
  ct.yaml
Labels: 1.9.0

#280 Add @TheAlgo and @DandyDeveloper as the default reviewer of PRs
  .github/CODEOWNERS
Labels: documentation

#281 [Backport 1.x] Add @TheAlgo and @DandyDeveloper as the default reviewer of PRs
  .github/CODEOWNERS
Labels: documentation

#282 [Backport 1.x] Backport 108ef6e to 1.x branch of #172 PR
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/README.md
  charts/opensearch/ci/ci-ingress-class-name-values.yaml
  charts/opensearch/ci/ci-rbac-enabled-values.yaml
  charts/opensearch/ci/ci-values.yaml
  charts/opensearch/templates/statefulset.yaml
  charts/opensearch/values.yaml
  ct.yaml
Labels: backport 1.x
