Repository opensearch-project/helm-charts, pull requests merged in 2022-05, with the labels that each got.

#258 Update charts to use 1.3.2 Version of OS/OSD
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: release

#260 Delete DCO check workflow as the app is taken care of it
  .github/workflows/dco-check.yaml
Labels: cicd

#265 1.x branch to have 1.x releases
  .github/workflows/release.yaml
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  ct.yaml
Labels: enhancement, backport 1.x

#262 convert main to 2.x
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: enhancement

#264 [Backport 1.x] Add contribution version and branching guides to readme.md
  CONTRIBUTING.md
  README.md
Labels: documentation, backport 1.x

#263 Add contribution version and branching guides to readme.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#270 Bump version to 2.0.0 app version
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: release, 2.0.0
