Repository opensearch-project/helm-charts, pull requests merged in 2023-05, with the labels that each got.

#423 Update the Readme.
  README.md
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/values.yaml
Labels: seasoned-contributor

#424 Increment OS and OSD version to 2.7.0
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: repeat-contributor

#417 Add imagePullPolicy to init container
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/statefulset.yaml
Labels: backport 1.x, first-time-contributor
