Repository opensearch-project/helm-charts, pull requests merged in 2023-06, with the labels that each got.

#439 Updated OS and OSD appVersion to 2.8.0
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: repeat-contributor

#434 fix: Avoid CrashLoop when keystore secret has no data
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/statefulset.yaml
Labels: backport 1.x, first-time-contributor

#445 fix: variable name in keystore import
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/statefulset.yaml
Labels: first-time-contributor

#443 [Backport 1.x] Avoid CrashLoop when keystore secret has no data
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/statefulset.yaml
Labels: first-time-contributor
