Repository opensearch-project/helm-charts, pull requests merged in 2024-05, with the labels that each got.

#540 Do Not mark 1.x releases as latest
  .github/workflows/release.yaml
Labels: bug, workflows

#542 Upgrade to OpenSearch and Dashboards 2.14.0
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: repeat-contributor

#545 Remove @bbarani as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/Chart.yaml
Labels: first-time-contributor

#546 Backport #545 maintainers to 1.x branch
  .github/CODEOWNERS
  MAINTAINERS.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/Chart.yaml
Labels: all-star-contributor
