Repository opensearch-project/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#589 [Fix] Missing TCP Protocol For Metrics in OpenSearch and OpenSearch Dashboards
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch-dashboards/templates/service.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/service.yaml
Labels: first-time-contributor

#586 feat(serviceMonitors): add option of additional Labels in serviceMonitor
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch-dashboards/templates/serviceMonitor.yaml
  charts/opensearch-dashboards/values.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/serviceMonitor.yaml
  charts/opensearch/values.yaml
Labels: backport 1.x, first-time-contributor

#596 Improve grammar in README
  README.md
Labels: first-time-contributor

#597 [Backport 1.x] Improve grammar in README
  README.md
Labels: documentation, backport 1.x, all-star-contributor

#591 Allow user-defined labels on pvcs
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/statefulset.yaml
  charts/opensearch/values.yaml
Labels: backport 1.x, first-time-contributor

#598 Upgrade to 2.17.0
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: valued-contributor
