Repository opensearch-project/helm-charts, pull requests merged in 2024-08, with the labels that each got.

#569 [Release 2.16.0] Helm charts update
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
Labels: seasoned-contributor

#570 Correct defaults for opensearchJavaOpts in README
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/README.md
Labels: first-time-contributor

#572 Fix changelog #570
  charts/opensearch/CHANGELOG.md
Labels: documentation, all-star-contributor

#571 [Backport 1.x] Correct defaults for opensearchJavaOpts in README
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/README.md
Labels: backport 1.x, all-star-contributor

#537 feat: Add serviceMonitor resource
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch-dashboards/README.md
  charts/opensearch-dashboards/templates/serviceMonitor.yaml
  charts/opensearch-dashboards/values.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/README.md
  charts/opensearch/templates/serviceMonitor.yaml
  charts/opensearch/values.yaml
Labels: first-time-contributor

#583 Update chart-releaser-action to 1.6.0 to consume the mark_as_latest param properly
  .github/workflows/release.yaml
Labels: enhancement, all-star-contributor, infra

#584 [Backport 1.x] Update chart-releaser-action to 1.6.0 to consume the mark_as_latest param properly
  .github/workflows/release.yaml
Labels: backport 1.x

#581 [Fix] OpenSearch and OpenSearch Dashboards Service Monitor Bug
  charts/opensearch-dashboards/CHANGELOG.md
  charts/opensearch-dashboards/Chart.yaml
  charts/opensearch-dashboards/README.md
  charts/opensearch-dashboards/templates/service.yaml
  charts/opensearch-dashboards/templates/serviceMonitor.yaml
  charts/opensearch-dashboards/values.yaml
  charts/opensearch/CHANGELOG.md
  charts/opensearch/Chart.yaml
  charts/opensearch/templates/serviceMonitor.yaml
Labels: backport 1.x, first-time-contributor
